Traceback (most recent call last):
  File "/home/gridsan/rgras/deep-kernel-transfer/train_regression.py", line 59, in <module>
    optimizer = torch.optim.Adam([{'params': model.model.parameters(), 'lr': 0.001},
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/optim/adam.py", line 33, in __init__
    super().__init__(params, defaults)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/optim/optimizer.py", line 192, in __init__
    self.add_param_group(param_group)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/optim/optimizer.py", line 535, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group
Traceback (most recent call last):
  File "/home/gridsan/rgras/deep-kernel-transfer/test_regression.py", line 51, in <module>
    model.load_checkpoint(params.checkpoint_dir)
  File "/home/gridsan/rgras/deep-kernel-transfer/methods/UnLiMiTDR_regression.py", line 113, in load_checkpoint
    ckpt = torch.load(checkpoint)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2023a-pytorch/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './save/checkpoints/QMUL/Conv3_UnLiMiTDR'
